### ISSUE TITLE
geoserver-rc.aodn.org.au down

### ISSUE THREAD

**Issue by julian1** [aodn/VIT#10]
<a href="https://github.com/julian1"><img src="https://avatars.githubusercontent.com/u/4312379?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [julian1](https://github.com/julian1)**
_Sunday Oct 30, 2016 at 23:54 GMT_
_Originally opened as https://github.com/aodn/internal-discussions/issues/311_

----

```
Caused by: org.postgresql.util.PSQLException: FATAL: too many connections for role "geoserver_rc"
        at org.postgresql.Driver$ConnectThread.getResult(Driver.java:365)
        at org.postgresql.Driver.connect(Driver.java:288)
        at org.apache.tomcat.dbcp.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.tomcat.dbcp.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.tomcat.dbcp.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
        at org.apache.tomcat.dbcp.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
        ... 118 more
```

**Comment by julian1** [comment]
<a href="https://github.com/julian1"><img src="https://avatars.githubusercontent.com/u/4312379?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [julian1](https://github.com/julian1)**
_Monday Oct 31, 2016 at 00:42 GMT_

----

jndi shows max active is 10,

```
   <Resource name="jdbc/harvest_read" auth="Container"
            type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
            url="jdbc:postgresql://db-rc.aodn.org.au:5432/harvest?loginTimeout=1000&amp;ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory"
            validationQuery="SELECT 1"
            username="geoserver_rc" password="xxxx"
            maxActive="10" maxIdle="5" maxWait="-1"
```

But the db shows 11 connections,
 


```
 
harvest=# select client_addr from pg_stat_activity where usename = 'geoserver_rc' ;
 client_addr  
--------------
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
 144.6.232.15
Which matches the limit,
(11 rows)


harvest=# select count( client_addr ) from pg_stat_activity where usename = 'geoserver_rc' ;
 count 
-------
    11
(1 row)

```

which matches the limit for the user

```
Which matches the limit,
harvest=# \du geoserver_rc
                    List of roles
  Role name   |   Attributes   |      Member of       
--------------+----------------+----------------------
 geoserver_rc | 11 connections | {harvest_read_group}

harvest=# 
```
 
so I have no idea.

**Comment by julian1** [comment]
<a href="https://github.com/julian1"><img src="https://avatars.githubusercontent.com/u/4312379?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [julian1](https://github.com/julian1)**
_Monday Oct 31, 2016 at 00:59 GMT_

----

So I stopped tomcat and 14-nec still shows 11 connections.

It's looking a bit like the kind of VM behavior that killed 14-nsp-mel.

At the moment, it's not even possible to get a psql connection to verify.

**Comment by julian1** [comment]
see https://github.com/aodn/internal-discussions/issues/311

**Comment by mhidas** [comment]
Has there been any progress on this?
I can bring up the web interface on geoserver-rc, but there are no layers to preview and none seem to load in portal-rc either.

**Comment by julian1** [comment]
@lwgordonimos is still working on it

**Comment by julian1** [comment]
with Nectar people
