### ISSUE TITLE
ANFOG_RT index deletion fails

### ISSUE THREAD

**Issue by bpasquer** [aodn/VIT#14]
Exception in ANFOG_RT pipeline causing the index deletion of previous file to fail. Issue appeared yesterday. This is the error message form  talend log:

"Exception in component iUpdateSpatialExtent_1
it.geosolutions.geonetwork.exception.GNLibException: Error parsing GN response: Error on line 31 of document http://www.w3.org/TR/html4/loose.dtd: The declaration for the entity "HTML.V
ersion" must end with '>'.
        at it.geosolutions.geonetwork.op.GNMetadataGet.parse(GNMetadataGet.java:101)
        at it.geosolutions.geonetwork.op.GNMetadataGet.get(GNMetadataGet.java:64)
        at it.geosolutions.geonetwork.op.GNMetadataGet.get(GNMetadataGet.java:58)
        at it.geosolutions.geonetwork.GNClient.get(GNClient.java:122)
        at anfog_rt.updatemetadata_0_1.UpdateMetadata.iUpdateSpatialExtent_1Process(UpdateMetadata.java:523)
        at anfog_rt.updatemetadata_0_1.UpdateMetadata.runJobInTOS(UpdateMetadata.java:804)
        at anfog_rt.updatemetadata_0_1.UpdateMetadata.runJob(UpdateMetadata.java:651)
        at anfog_rt.anfog_rt_harvester_0_1.ANFOG_RT_harvester.tRunJob_4Process(ANFOG_RT_harvester.java:1878)
        at anfog_rt.anfog_rt_harvester_0_1.ANFOG_RT_harvester.tRunJob_2Process(ANFOG_RT_harvester.java:1611)
        at anfog_rt.anfog_rt_harvester_0_1.ANFOG_RT_harvester.tRunJob_1Process(ANFOG_RT_harvester.java:1434)
        at anfog_rt.anfog_rt_harvester_0_1.ANFOG_RT_harvester.tRunJob_5Process(ANFOG_RT_harvester.java:1263)
        at anfog_rt.anfog_rt_harvester_0_1.ANFOG_RT_harvester.runJobInTOS(ANFOG_RT_harvester.java:3684)
        at anfog_rt.anfog_rt_harvester_0_1.ANFOG_RT_harvester.main(ANFOG_RT_harvester.java:3476)
Caused by: org.jdom.input.JDOMParseException: Error on line 31 of document http://www.w3.org/TR/html4/loose.dtd: The declaration for the entity "HTML.Version" must end with '>'.
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:465)
        at org.jdom.input.SAXBuilder.build(SAXBuilder.java:851)
        at it.geosolutions.geonetwork.op.GNMetadataGet.parse(GNMetadataGet.java:98)
        ... 12 more
Caused by: org.xml.sax.SAXParseExceptionpublicId: -//W3C//DTD HTML 4.01 Transitional//EN; systemId: http://www.w3.org/TR/html4/loose.dtd; lineNumber: 31; columnNumber: 3; The declaration for the entity "HTML.Version" must end with '>'. "

**Comment by julian1** [comment]
maybe related, https://github.com/aodn/VIT/issues/12

**Comment by mhidas** [comment]
Seeing the same issue in some ANMN pipelines. See e.g.
```
/mnt/ebs/log/data-services/ANMN_NRS_RT/IMOS_ANMN-NRS_MT_20161109T231108Z_NRSMAI_FV00_NRSMAI-Surface-21-2016-11-MET-realtime.nc.CW7yM9.20161129-113200.log
/mnt/ebs/log/data-services/ANMN_QLD_RT/IMOS_ANMN-QLD_CKOSTUZ_20151110T013027Z_GBRPPS_FV00_GBRPPS-1511-WQM-71-realtime.nc.LirQdB.20161129-113510.log
/mnt/ebs/log/data-services/ANMN_AM/IMOS_ANMN-AM_KST_20160912T080000Z_GBRWIS_FV00_GBRWIS-CO2-1609-realtime-raw_END-20161127T040000Z_C-20161127T042520Z.nc.20161128-154020.log
```

**Comment by bpasquer** [comment]
The ANFOG_RT pipeline is up. Maybe you should try pushing your ANMN files through the pipeline again @mhidas

**Comment by mhidas** [comment]
@bpasquer Thanks for the heads up. Yes, they all seem to be working ok now.
